# Built with Flutter 3.7.12, CocoaPods 1.11.3
name: tommylingo
description: Tommylingo Mobile App
version: 23.5.15+6

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 2.0.0         # state management
  http: 0.13.6                # http support
  xml: 6.2.2                  # xml parsing
  tuple: 2.0.1                # tuples
  #fluttertoast: 8.2.1         # hint messages TODO: switch to bot_toast: 4.0.4 or Scaffold
  flutter_typeahead: 4.3.8    # text field with suggestions

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
