# Build with Flutter 3.7.12, CocoaPods 1.11.3
name: tommypass
description: Mobile App for TommyPass
version: 23.5.26+1            # by calver.org; before build set up the auth token!

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: 2.0.0         # state management
  http: 0.13.6                # http support
  json_annotation: 4.8.1      # json auto-generation
  flutter_typeahead: 4.3.8    # text field with suggestions
  shared_preferences: 2.1.1   # key-value storage for passcode

dev_dependencies:
  flutter_lints: 2.0.1
  build_runner: 2.3.3         # json auto-generation
  json_serializable: 6.6.2    # json auto-generation

flutter:
  uses-material-design: true
